### ISSUE TITLE
Will you continue to update that database?

### ISSUE THREAD

**Issue by alexandrsanches** [mesenrj/covid19_br#1]
I was using that database to create a few graphics before MS changed it, and my entire code is based on it. My question is if you pretend to continue update that database or just posted the last available version.

Thank you.

**Comment by mesenrj** [comment]
Sorry that only saw it now. I started this repository when MS changed the notification from states only to city level granularity. When they did that they erased the historical data for states, but that only happened for a single day (next day the historical data was available again).

Now I started accumulating data again since there is a lot of uncertainty if the CSV files from covid.saude.gov.br will be kept public. This time I intend to keep the repository updated to avoid data losses.

I'm still working on what's the best structure for storing the data is, since I have some other files I want to upload as well (mainly from Rio de Janeiro city).

**Comment by alexandrsanches** [comment]
Thank you!
